import type { Metadata } from "next";
import "./globals.css";
import { Figtree } from "next/font/google";

const figTree = Figtree({ subsets: ["latin"] });

export const primaryFont = figTree?.className;
export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${primaryFont} antialiased`}>{children}</body>
    </html>
  );
}
